services:
  api:
    build: .
    container_name: badge-generator-api
    depends_on:
      - cache
    ports:
      - "127.0.0.1:9080:80"
    restart: unless-stopped
    volumes:
      - ./.config/config.toml:/app/.config/config.toml:ro
      - ./templates:/app/templates:ro
    networks:
      - badge-generator-network

  cache:
    image: redis:7-alpine3.21
    container_name: badge-generator-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - badge-generator-network

volumes:
  redis-data:

networks:
  badge-generator-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: "1450"
