services:
  api:
    build:
      context: .
      network: host
    container_name: badge-generator-api
    depends_on:
      - cache
    ports:
      - "127.0.0.1:9080:80"
    restart: unless-stopped
    volumes:
      - ./.config/config.toml:/app/.config/config.toml:ro
      - ./templates:/app/templates:ro

  cache:
    image: redis:7-alpine3.21
    container_name: badge-generator-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  redis-data:
